### ISSUE TITLE
python doesn't find keras

### ISSUE THREAD

**Issue by kecman** [cambridgecoding/machinelearningbootcamp#2]
Hi, I'm attending the course this weekend and I followed the setup instructions in the README. I have an issue getting keras working. I can't find the keras package when I use anaconda2 python:

```
matija@matija-tpx1: /home/matija
$ which python                     
/home/matija/anaconda2/bin/python
matija@matija-tpx1: /home/matija
$ python --version
Python 2.7.12 :: Anaconda custom (64-bit)
matija@matija-tpx1: /home/matija
$ python -c "import keras" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named keras
```

It works when I use my system python though:

```
matija@matija-tpx1: /home/matija
$ /usr/bin/python --version
Python 2.7.12
matija@matija-tpx1: /home/matija
$ /usr/bin/python -c "import keras"
Using Theano backend.
```
Using `/usr/bin/python -v` I figured out I have keras installed at `/usr/local/lib/python2.7/dist-packages/keras`, do I need to do something to be able to import these files using the anaconda2 python?

When I do the last step to run the `load_libraries.ipynb` it doesn't find keras either, I tried with the conda root kernel and the default kernel. I also tried using `conda install jupyter` and doing a similar thing and that didn't work either. I guess this keras thing is only a problem for Day 2 so I could wait until then.

**Comment by tlienart** [comment]
I'm not 100% sure, however Anaconda has ways of having several independent environments in which you have to reinstall each library which may be your problem. For example you can have a Python 2 and Python 3 environment running and in each of those two you'd have to reinstall Keras (or any extra library that you may be using). 

Can you maybe add here how you installed Anaconda (why is it `custom` ?) and to maybe try reinstalling `pip install keas` when you're sure that you're using the conda environment?

**Comment by kecman** [comment]
Thanks a lot, I managed to identify the problem following your suggestions, I think somehow I run a different `pip` when i use `sudo`:

```
matija@matija-tpx1: /home/matija/Dropbox/repos/machinelearningbootcamp
$ sudo which pip
/usr/local/bin/pip
matija@matija-tpx1: /home/matija/Dropbox/repos/machinelearningbootcamp
$ which pip
/home/matija/anaconda2/bin/pip
```

Wierd.. anyway I fixed the problem using:

`/home/matija/anaconda2/bin/pip install keras`

**Comment by tlienart** [comment]
last thing to check to make sure everything is fine, could you:

* `jupyter notebook`
* create a new notebook, add `import keras` in the first cell
* check that it can be run (MAJ+ENTER to execute the cell)

and thanks for reporting, it's useful to know how to fix that kind of issues.

**Comment by kecman** [comment]
Yes, that works as well :)
